version: "3.8"

services:
  db_dealer:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"
    restart: on-failure

volumes:
  postgres_data: