version: '3.7'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/usr/src/app/
    ports:
      - "8008:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    ports:
      - "30003:5432"


