version: "3.8"

services:
  db_dealer:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-dealer-web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db_dealer
    restart: always
#    volumes:
#      - ./:usr/src/app/

volumes:
  postgres_data: