version: "3.8"

services:
  db_dealer:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"
    env_file:
      - .env
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealer-backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db_dealer

volumes:
  postgres_data: