version: "3.8"

services:
  db_dealer:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealer-backend
    restart: always
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db_dealer

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dealer-frontend
    volumes:
      - react_build:/react/build

  nginx:
    image: nginx:latest
    container_name: dealer-nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - frontend
      - backend

volumes:
  react_build:
  postgres_data: