# Generated by Django 4.0.4 on 2022-04-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
        migrations.AlterField(
            model_name='offer',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='apps.carprice'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN'), ('RUB', 'RUB')], default='USD', max_length=6),
        ),
    ]
