# Generated by Django 4.0.4 on 2022-04-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_offer_currency_remove_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealeraddress',
            name='dealer',
        ),
        migrations.AddField(
            model_name='dealer',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.dealeraddress'),
        ),
    ]
