# Generated by Django 4.0.4 on 2022-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_profile_balance_profile_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PROCESS', 'PROCESS')], default='PROCESS', max_length=7),
        ),
    ]
